[package]
name = "client"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
gloo = { version = "0.11.0", features = ["gloo-net"] }
wasm-bindgen-futures = "0.4.51"
web-sys = "0.3.78"
yew = { version = "0.21.0", features = ["csr"] }
